version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test3001Project
  gitServerName: rlakshitha0912
  gitUrl: https://github.com/rlakshitha0912
  gitUsername: rlakshitha0912
  gitBranch: main
services:
- serviceName: project.test3001.integrations:date3
  packages:
  - name: Test3001Project
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
